# Site/SEO settings
email: luisgsalgueiro@gmail.com
#baseurl: ""
permalink: /:year/:title/
google_analytics: 

name: Luís Salgueiro
title: Luís Salgueiro
description: >
  Portfolio website for composer Luís Salgueiro.
url: http://lsalgueiro.netlify.app
twitter_username: canoxa
default_img: /assets/images/DSCF3917.jpg
social:
  - name: soundcloud
    url: https://soundcloud.com/l-salgueiro
  - name: twitter
    url: https://twitter.com/canoxa
  - name: instagram
    url: https://www.instagram.com/luissalgueiro/
  - name: github
    url: https://github.com/lsalgueiro


# Contact settings
contact_img: /assets/images/DSCF3903.jpg
formcarry: https://formcarry.com/s/k51zQwtMSrf2

# Disqus settings
#disqus: test-apkdzgmqhj

# MailChimp settings
#mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
#mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Luís Salgueiro
    bio: Luís Salgueiro is a composer of instrumental, electronic and mixed music that draws from and pushes against discontinuities in timbres, time scales, embodied cognition.
    #url: http://thomasvaeth.com

# Custom collections
collections:
  works:
    output: true

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Luís Salgueiro'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - scripts
  - style-guide.html
